services:
 bot-mini:
    image: ghcr.io/wamom-question/nenelobo/bot-mini:latest
    volumes:
      - ./data:/app/data
    env_file: .env
  #  depends_on:
  #    - python-result-calc
  #    - announce-fetcher
  #    - bot
    restart: always